  0%|                                                                                                                                  | 0/8 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/jzhanggr/jzhanggr001/Uncertainty_Experiments/new_dpo.py", line 110, in <module>
    main()
  File "/home/jzhanggr/jzhanggr001/Uncertainty_Experiments/new_dpo.py", line 104, in main
    dpo_trainer.train()
  File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 2178, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/data_loader.py", line 454, in __iter__
    current_batch = next(dataloader_iter)
  File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2807, in __getitems__
    batch = self.__getitem__(keys)
  File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2803, in __getitem__
    return self._getitem(key)
  File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2787, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
  File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 583, in query_table
    _check_valid_index_key(key, size)
  File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 536, in _check_valid_index_key
    _check_valid_index_key(int(max(key)), size=size)
  File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 526, in _check_valid_index_key
    raise IndexError(f"Invalid key: {key} is out of bounds for size {size}")
IndexError: Invalid key: 12 is out of bounds for size 0
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/jzhanggr/jzhanggr001/Uncertainty_Experiments/new_dpo.py", line 110, in <module>
[rank0]:     main()
[rank0]:   File "/home/jzhanggr/jzhanggr001/Uncertainty_Experiments/new_dpo.py", line 104, in main
[rank0]:     dpo_trainer.train()
[rank0]:   File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 1885, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 2178, in _inner_training_loop
[rank0]:     for step, inputs in enumerate(epoch_iterator):
[rank0]:   File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/data_loader.py", line 454, in __iter__
[rank0]:     current_batch = next(dataloader_iter)
[rank0]:   File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
[rank0]:     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
[rank0]:   File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
[rank0]:     data = self.dataset.__getitems__(possibly_batched_index)
[rank0]:   File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2807, in __getitems__
[rank0]:     batch = self.__getitem__(keys)
[rank0]:   File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2803, in __getitem__
[rank0]:     return self._getitem(key)
[rank0]:   File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2787, in _getitem
[rank0]:     pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
[rank0]:   File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 583, in query_table
[rank0]:     _check_valid_index_key(key, size)
[rank0]:   File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 536, in _check_valid_index_key
[rank0]:     _check_valid_index_key(int(max(key)), size=size)
[rank0]:   File "/export/project/jzhanggr/miniconda3/envs/lmflow/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 526, in _check_valid_index_key
[rank0]:     raise IndexError(f"Invalid key: {key} is out of bounds for size {size}")
[rank0]: IndexError: Invalid key: 12 is out of bounds for size 0